from django.contrib import admin
from django.urls import path
from client import client_views
urlpatterns = [
    path('index/',client_views.home),
    path('signin/',client_views.login),
    path('forgot/',client_views.forgot_password),
    path('send_otp/',client_views.send_otp),
    path('set_pass/',client_views.set_password),
    path('banner/',client_views.banner_search),
    path('banner/<int:id>',client_views.banner_search),
    path('banner1/',client_views.banner_search1),
    path('banner1/<int:id>',client_views.banner_search1),
    path('full_details/<int:id>',client_views.full_details),
    path('signup/',client_views.signup),
    path('otp_verify/',client_views.otp_verification),
    path('edit_profiles/',client_views.edit_profile),
    path('wishlist/',client_views.wishlist),
    path('booking/',client_views.booking),
    path('submitpg/',client_views.submitpg),
    path('pglist/',client_views.pg_list),
    path('in_feed/',client_views.insert_feedback),
    path('bookpg/',client_views.book_pg),
    path('bookpg/<int:id>',client_views.book_pg),
    path('client_header_menu/',client_views.load_menu),
    path('client_header_area/',client_views.load_area),
    path('add_wishlist/',client_views.add_to_wishlist),
    path('del_wishlist/<int:id>',client_views.delete_form_wishlist),
    path('inquiry/',client_views.insert_inquiry),
    path('faq/',client_views.faq),
    path('logout/',client_views.client_logout),
    path('sort/',client_views.sort_data),
    path('search_product/', client_views.search, name='pro_search'),
    path('cal_date/',client_views.add_months),
    path('contact/',client_views.contact),
    path('checkout/',client_views.client_Checkout),
    # path('place_booking_online/',client_views.place_order_online),
    path('place_booking_online/<int:id>',client_views.place_order_online),
    path('client_header_package/',client_views.load_package),
    # path('send_mail/',client_views.send_main_on_booking_end),
]