# Generated by Django 4.2.5 on 2024-03-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=20)),
                ('area_pin_code', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('cate_name', models.CharField(max_length=20)),
                ('cate_desc', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('faci_id', models.AutoField(primary_key=True, serialize=False)),
                ('faci_name', models.CharField(max_length=20)),
                ('faci_desc', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='Pg_details',
            fields=[
                ('pg_id', models.AutoField(primary_key=True, serialize=False)),
                ('pg_name', models.CharField(max_length=20)),
                ('pg_image', models.CharField(max_length=40)),
                ('pg_address', models.CharField(max_length=100)),
                ('pg_email', models.EmailField(max_length=254, unique=True)),
                ('pg_contact', models.CharField(max_length=13)),
                ('pg_desc', models.CharField(max_length=200)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.area')),
                ('cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.category')),
            ],
            options={
                'db_table': 'pg_details',
            },
        ),
        migrations.CreateModel(
            name='Pg_owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_first_name', models.CharField(max_length=30)),
                ('owner_last_name', models.CharField(max_length=30)),
                ('owner_contact_no', models.CharField(max_length=13)),
                ('owner_email_id', models.EmailField(max_length=254, unique=True)),
                ('owner_address', models.CharField(max_length=200)),
                ('owner_gender', models.CharField(max_length=1)),
                ('owner_password', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('otp_used', models.IntegerField()),
            ],
            options={
                'db_table': 'pg_owner',
            },
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('room_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type_name', models.CharField(max_length=20)),
                ('room_desc', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'room_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=13)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=1)),
                ('password', models.CharField(max_length=15)),
                ('is_admin', models.IntegerField()),
                ('otp', models.CharField(max_length=6)),
                ('otp_used', models.IntegerField()),
                ('is_verify', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.pg_details')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.user')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
        migrations.CreateModel(
            name='Pg_rooms',
            fields=[
                ('pg_rooms_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_of_rooms', models.IntegerField()),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.pg_details')),
                ('room_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.room_type')),
            ],
            options={
                'db_table': 'pg_rooms',
            },
        ),
        migrations.CreateModel(
            name='Pg_facility',
            fields=[
                ('pg_facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('faci_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.facility')),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.pg_details')),
            ],
            options={
                'db_table': 'pg_facility',
            },
        ),
        migrations.AddField(
            model_name='pg_details',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.pg_owner'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('pack_id', models.AutoField(primary_key=True, serialize=False)),
                ('pack_name', models.CharField(max_length=20)),
                ('pack_desc', models.CharField(max_length=200)),
                ('pack_price', models.IntegerField()),
                ('pack_month', models.IntegerField()),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.pg_details')),
                ('room_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.room_type')),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_no', models.CharField(max_length=13)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('u_message', models.CharField(max_length=100)),
                ('response', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.user')),
            ],
            options={
                'db_table': 'inquiry',
            },
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('gallary_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=40)),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.pg_details')),
            ],
            options={
                'db_table': 'gallary',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_desc', models.CharField(max_length=200)),
                ('feed_date', models.DateField()),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.pg_details')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.user')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_date', models.DateField()),
                ('end_date', models.DateField()),
                ('book_desc', models.CharField(max_length=200)),
                ('payment_status', models.IntegerField()),
                ('book_status', models.IntegerField()),
                ('pack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.package')),
                ('pg_rooms_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.pg_rooms')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_admin.user')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
